### ISSUE TITLE
I needed some explanation about the following: "average k_pct for each K rate (in kg/ha) within each location (basically, averaging over reps)"

### ISSUE THREAD

**Issue by KVUGA** [leombastos/2024_ppa#11]
Can someone please explain what "k_pct" means and what does "reps" signifies?

**Comment by RegimarGarcia** [comment]
"k_pct" is Potassium expressed in percent by weight and "reps" are the number of blocks for which each treatment was applied, or repeated.

**Comment by KVUGA** [comment]
Thank you @RegimarGarcia
