### ISSUE TITLE
what codes can we use in plotting the following conditions?

### ISSUE THREAD

**Issue by KVUGA** [leombastos/2024_ppa#18]
I was going through the previous lectures, and I wanted to ask about the plots we made in the NASS data based classes (where spatial elements were not part of the codes). 
In most of the graphs, we've used "geom_line" to draw the graphs. What I want to ask is if it is necessary to use the "geom_line" option only, or can we choose others as well?

**Comment by leombastos** [comment]
We could've chosen others as well.
Here's a resource to get you going further with ggplot, including a cheatsheet and vignettes:
https://ggplot2.tidyverse.org
