### ISSUE TITLE
What does it mean? COTTON, UPLAND - PRODUCTION, MEASURED IN 480 LB BALES

### ISSUE THREAD

**Issue by KVUGA** [leombastos/2024_ppa#21]
Does it mean 480Lb is equal to one bale? Which in turn means 217.72kg. Am I right? Kindly confirm

**Comment by leombastos** [comment]
The unit of your category is number of bales, where each bale weights 480 lbs.

**Comment by KVUGA** [comment]
Okay, thank you.
