### ISSUE TITLE
Which year should I consider the final year?

### ISSUE THREAD

**Issue by KVUGA** [leombastos/2024_ppa#28]
The data I am working on, when downloaded has rows of even the year 2023, but there's not a single repoted entry in it. Should I consider it to be the latest one, or should I stop at 2022.

**Comment by NivaIbrahim** [comment]
If you don't have any values in 2023, then may be you can't proceed with NA values. Why don't you remove the rows!

**Comment by NivaIbrahim** [comment]
Only Dr. Leo can answer that. I am no help here. But, If I were you I would go for 2022 as there is no value for 2023.

**Comment by KVUGA** [comment]
@NivaIbrahim , Yes, that's what I have been thinking to go with. Still, one question remains, that is, for the first question, which asks for the latest year specifically, should I go with 2022 or 2023. @leombastos please consider this case and suggest accordingly.

**Comment by leombastos** [comment]
Kumar, you should include all years that have data reported.

Are you saying there is no data at all? If that's the case then something went wrong.

Show me a screenshot of your data frame showing the columns year, county, and value.

**Comment by KVUGA** [comment]
![Screenshot (8)](https://github.com/leombastos/2024_ppa/assets/155990437/2ca9f468-5088-4d3e-a219-28641b4f5a3d)
![Screenshot (9)](https://github.com/leombastos/2024_ppa/assets/155990437/a9b8c11c-9bb1-49a5-9e1e-1cd759c00c9d)

**Comment by leombastos** [comment]
Just keep the rows where you have data for your category and use that throughout the project

**Comment by KVUGA** [comment]
Thank you for your response. I am doing that. But still, my last question here is:
In the first question, it asks for the latest year from the data set. Which one should I consider? 
2023 as there is mention of it, or 2022 because the reportings are up to this year only?
