### ISSUE TITLE
Help needed in deciding a field

### ISSUE THREAD

**Issue by KVUGA** [leombastos/2024_ppa#30]
I am not sure how to choose a field. Can you please help me with it @leombastos

**Comment by Reneliza** [comment]
Hi, Kumar. I suggested the Dooley field at Sanford Stadium to Dr. Bastos, thinking it would be an interesting area. However, I realize the assignment is asking for an agricultural field. I remember one of our crops in the Forage Breeding Lab under Dr. Ali Missaoui is tall fescue. The field is in the West Unit of JPC in Watkinsville, GA. I am unsure which of these options Dr. Bastos would advise.

**Comment by leombastos** [comment]
@KVUGA you can use these field centroids (in WGS84):
-83.52355 31.49117 

This field is grown with bermuda grass.

Thanks,

Leo.

**Comment by KVUGA** [comment]
Thanks a lot, @leombastos 
and thank you @Reneliza for trying to identify one for me !
