### ISSUE TITLE
Needed an explantion of the additional comments on running library("gganimate")

### ISSUE THREAD

**Issue by KVUGA** [leombastos/2024_ppa#5]
After I run the command, libraby("gganimate") I see furthen information too. Can anyone explain this to me?
> library("gganimate")
No renderer backend detected. gganimate will default to writing frames to separate files
Consider installing:
- the `gifski` package for gif output
- the `av` package for video output
and restarting the R session

Attaching package: ‘gganimate’

The following object is masked from ‘package:raster’:

    animate

>

**Comment by leombastos** [comment]
Hi Kumar,

This is just a message saying what packages are used for different outputs when you use package gganimate.
It is just for your reference, no need to do anything about it.

**Comment by KVUGA** [comment]
Dear Dr Bastos,
Thank you for the explanation.
