### ISSUE TITLE
Can anyone help me with how to work around yield interpolation. In the class Dr Bastos used three data to find mean, cv, and sd, but how can we do that from one year. 

### ISSUE THREAD

**Issue by KVUGA** [leombastos/2024_ppa#65]

**Comment by ClintHerndon** [comment]
I classified yields as low, medium, and high.  I'm not sure if this is the correct way to go about it but it worked for me

**Comment by KVUGA** [comment]
Okay, thanks. I did that, and It worked.
I have another issue now.
I will generate a new issue for it if this doesn't work.
