### ISSUE TITLE
Assignment #1

### ISSUE THREAD

**Issue by leombastos** [leombastos/2024_ppa#7]

**Comment by Reneliza** [comment]
![plot_a1_CEJALVO](https://github.com/leombastos/2024_ppa/assets/128764190/a1558205-cb06-4e0f-b14a-6ab1418e1746)

**Comment by Reneliza** [comment]
![plot_a1_CEJALVO](https://github.com/leombastos/2024_ppa/assets/128764190/71b671c2-8357-4bfa-94bf-9fb87268a11c)

**Comment by DaltonBeasley** [comment]
![plot1_a1_Beasley](https://github.com/leombastos/2024_ppa/assets/156206493/92e9051a-97ab-4606-9c25-31e8abb318f5)

**Comment by KVUGA** [comment]
![plot_a1_VAIBHAV](https://github.com/leombastos/2024_ppa/assets/155990437/4668d281-2767-485e-aacf-146802cdb75c)

**Comment by ClintHerndon** [comment]
![plot_1a_Herndon](https://github.com/leombastos/2024_ppa/assets/155988219/877c0a60-44f8-400e-a402-0623bb22517b)

**Comment by NivaIbrahim** [comment]
![plot_a1_Niva](https://github.com/leombastos/2024_ppa/assets/152580189/25e253ea-488a-415c-81ed-e9a112e41eb0)

**Comment by NivaIbrahim** [comment]
On second Class as you asked question how we can show favcrop in the plot and I replied to use "factor instead of mentioning color argument. As i was thinking that those are categorical so we can use factor argument. But I was silly and forgot to mention color first. 
color=factor(favcrop) also works as same.
Thank you!

**Comment by Vincius-Trevisan** [comment]
![plot1](https://github.com/leombastos/2024_ppa/assets/156142673/b2751eef-28e4-47f0-837b-c7f42517f472)

**Comment by Vincius-Trevisan** [comment]
![plot1](https://github.com/leombastos/2024_ppa/assets/156142673/86e35bbd-f087-45c4-8503-21208c2b07b3)

**Comment by ss59095** [comment]
![plot_a1_SHRESTHA](https://github.com/leombastos/2024_ppa/assets/155988308/77352ca8-89c6-4cc6-90a7-0c4d5ba5f6bc)

**Comment by Jazib001** [comment]
![plot_a1_Irfan](https://github.com/leombastos/2024_ppa/assets/156104871/710a6ecd-de69-4d74-b802-f6dd979ea9d6)

**Comment by dcurles12** [comment]
![plot1_a1_Curles](https://github.com/leombastos/2024_ppa/assets/155988196/1a532485-e25a-4015-89fa-79d58b536480)

**Comment by jrolando0804** [comment]
![plot_a1_Orellana](https://github.com/leombastos/2024_ppa/assets/155988761/cfbe58ab-aa9a-4245-ae04-84a9692995ae)

**Comment by ujjwalsigdel** [comment]
![plot_a1_SIGDEL](https://github.com/leombastos/2024_ppa/assets/123664580/4df5cbf0-6e65-4e99-96a9-b0b5318ef324)

**Comment by AmrinderJakhar98** [comment]
![plot_a1_Jakhar](https://github.com/leombastos/2024_ppa/assets/122116136/86661c3d-4f68-4260-b49b-71889ed16853)

**Comment by RegimarGarcia** [comment]
![Plot_a1_Santos png](https://github.com/leombastos/2024_ppa/assets/155988248/cb9e9a16-c8e2-40a7-9466-129368c783e7)
